---
- hosts: all
  become: true
  tasks:
    - name: Install haproxy
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - haproxy
