Vagrant.configure("2") do |config|
   config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
    end

  config.vm.define "loadbalancer" do |loadbalancer|
    loadbalancer.vm.box = 'bento/ubuntu-20.04'
    loadbalancer.vm.hostname = "loadbalancer"
    loadbalancer.vm.network :private_network, ip: "192.168.10.15"
    loadbalancer.vm.network "forwarded_port", guest: 80, host: 3000
    loadbalancer.vm.network "forwarded_port", guest: 8404, host: 8404
    loadbalancer.vm.provision "ansible" do |ansible|
            ansible.playbook = "loadbalancer-playbook.yml"
        end
  end
end
